### ISSUE TITLE
Multiple in an out paths

### ISSUE THREAD

**Issue by FlorianFusseder** [coderedcorp/django-sass#1]
Hello,
according to the help text it should be possible to define multiple paths for in and out, but i cannot get i to work. 
Is it possible? If yes could you add some clarification in the README?

**Comment by vsalvino** [comment]
The input and output can be a single file or single directory. It does not support multiple.

For example (files):

```
$ python manage.py sass /path/to/in.scss /path/to/out.css
```

For directories, it will search for all of the `.scss` files in the directory and output them to similarly named `.css` files in the output directory.

```
$ python manage.py sass /path/to/scss-dir/ /path/to/css-dir/
```
