### ISSUE TITLE
command not found error when trying to run compile...

### ISSUE THREAD

**Issue by NickADD** [coderedcorp/django-sass#5]
Forgive my n00bishness.
I installed django-sass in pycharm from the terminal.  No problem.  I added it to my installed_apps in my django project.  I then ran the command:
 python manage.py sass path/path/*.scss path/path/*.css -g
but I get an error that the command is not found.
When I run pip freeze the output shows that django-sass is in fact there.
When I run python manage.py help though, I do not see 'sass' as an available subcommand.  What am I doing wrong here?  Thanks for reading and for making this.  Can't wait to get it working for me.

**Comment by vsalvino** [comment]
Is it possible your python and pip are actually on different paths? Try `python -m pip freeze` and see if it is in there.

Also, for the INSTALLED_APPS, make sure it is available in whatever settings file you normally use, if you have more than one. You can manually specify a different settings file with `python mange.py sass --settings=project.settings [other options]`
